"""Phase C structured tool protocol and single-call executor.

ZOE_PHASE_A1_DESIGN.md §8.2 (tool call), §8.3/§24 (universal result envelope),
§8.4 (error taxonomy), §8.5 (executor contract), §10.1/§10.2 (Qwen wire format,
fabricated ``<tool_response>``), §22.3 (closed PolicyGate inputs).

This module holds:

- ``ToolCall``: the internal, frozen call record. Its ``id`` is generated by the
  orchestrator (``CallIdAllocator``); ids the model writes are ignored.
- ``strict_json_loads``: strict JSON (duplicate keys, NaN/Infinity, huge
  numbers, lone surrogates and over-deep nesting are rejected; no repair).
- ``QwenToolCallAdapter``: parses Qwen ``<tool_call>{"name": ..., "arguments":
  {...}}</tool_call>`` blocks into ``ToolCall`` records, with oversized-call
  limits and at most ``MAX_CALLS_PER_STEP`` calls per parse step.
  Model-supplied ``id`` / ``call_id`` / ``turn_id`` / ``step`` fields are
  tolerated and dropped (never authoritative); any other unexpected field is
  rejected. A ``<tool_response>`` block written by the model is fabricated: the
  block (including any ``<tool_call>`` nested inside it) is stripped and can
  never become a tool result, a call or an authorization; parsing continues
  normally after it. An unclosed ``<tool_response>`` is stripped to the end of
  the output; a stray ``</tool_response>`` tag is stripped.
- ``PolicyGate``: the authorization step. Its only inputs are the tool
  definition and the validated arguments (plus the turn-scoped B2 web decision
  derived from the current user message). The model's ``reason`` text is not
  an input.
- ``ToolExecutor``: the one execution authority for structured calls, in this
  fixed order: registry lookup -> version validation -> argument validation ->
  policy gate -> timeout boundary -> tool execution -> secret scan -> output
  schema validation -> universal result envelope (``tools.result_envelope.
  bound_result``). Every outcome is an envelope whose ``call_id`` is the
  ``ToolCall.id``; nothing raises past it and no traceback reaches the model or
  the user.

Phase C is not the model loop: nothing here calls the model, iterates, keeps
turn budgets, or is wired into ``brain/pipeline.py`` (that is Phase D).
"""

from __future__ import annotations

import contextvars
import json
import logging
import math
import re
import threading
import time
import uuid
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Mapping

from core.safe_errors import TypedSafeError, log_safe_exception
from plugins.tool_definition import ArgumentError, PermissionClass, freeze, thaw
from tools.result_envelope import (
    CANONICAL_ERROR_TYPES,
    PROTOCOL,
    ErrorType,
    ResultStatus,
    bound_result,
    error_envelope,
    make_envelope,
)
from tools.secret_scan import scan_and_redact

if TYPE_CHECKING:  # pragma: no cover
    from plugins.tool_definition import ToolDefinition
    from tools.tool_catalog import ToolRegistry

logger = logging.getLogger(__name__)
audit_logger = logging.getLogger("zoe.tools.audit")

# ---------------------------------------------------------------------------
# Limits
# ---------------------------------------------------------------------------

MAX_REASON_CHARS = 200  # §8.2
MAX_CALLS_PER_STEP = 3  # §10.3 (PARSE -> POLICY with N <= 3 per step)
MAX_TOOL_CALL_CHARS = 4096  # one <tool_call> JSON payload
MAX_MODEL_OUTPUT_CHARS = 32 * 1024  # whole model output considered for parsing
MAX_JSON_DEPTH = 8
MAX_JSON_NUMBER_CHARS = 32
MAX_TOOL_NAME_CHARS = 64

TOOL_CALL_OPEN = "<tool_call>"
TOOL_CALL_CLOSE = "</tool_call>"
# Fabricated tool responses (§10.2). Case-insensitive, tolerant of spacing and
# attributes so variants cannot slip through as prose that later looks real.
_RESPONSE_OPEN = re.compile(r"<\s*tool_response\b", re.IGNORECASE)
_RESPONSE_CLOSE = re.compile(r"<\s*/\s*tool_response\b[^>]*>?", re.IGNORECASE)

# Expected wire fields (Qwen ``name`` / ``arguments`` plus optional ``reason``
# and ``tool_version``, both validated).
_WIRE_KEYS = frozenset({"name", "arguments", "reason", "tool_version"})
# Model-supplied metadata: tolerated on the wire, NEVER authoritative, dropped
# before a ToolCall is built. Their values are ignored whatever their type, but
# the whole payload still passed strict JSON (duplicate keys, NaN/Infinity,
# number size, depth) and the per-call size limit. The orchestrator alone
# supplies ``ToolCall.id`` / ``turn_id`` / ``step``.
_IGNORED_WIRE_KEYS = frozenset({"id", "call_id", "turn_id", "step"})

_CALL_ID_RE = re.compile(r"^call_[0-9a-f]{24}$")
_TURN_ID_RE = re.compile(r"^[A-Za-z0-9_\-]{1,64}$")
_TOOL_NAME_RE = re.compile(r"^[A-Za-z0-9_.\-]{1,%d}$" % MAX_TOOL_NAME_CHARS)
_VERSION_RE = re.compile(r"^[1-9][0-9]{0,3}(?:\.[0-9]{1,4}){0,2}$")
_CONTROL_CHARS = re.compile(r"[\x00-\x08\x0b-\x1f\x7f]")

# ---------------------------------------------------------------------------
# Error vocabulary
# ---------------------------------------------------------------------------
#
# Web results keep B2's eight canonical ``ErrorType`` values. Non-web tool
# outcomes use the A.1 §8.4 taxonomy and keep B1's filesystem ``error_type``
# names and B3's calculator types unchanged.

UNKNOWN_TOOL = "unknown_tool"
UNSUPPORTED_VERSION = "unsupported_version"
INVALID_ARGUMENTS = "invalid_arguments"
MALFORMED_CALL = "malformed_call"
PERMISSION_DENIED = "permission_denied"
INTERNAL_ERROR = "internal_error"
SENSITIVE_CONTENT = "sensitive_content"

# B1 filesystem error types that mean "policy refused" (status: denied).
FILESYSTEM_DENIED_TYPES = frozenset(
    {
        "path_outside_workspace",
        "symlink_escape",
        "sensitive_path",
        "sensitive_content",
        "internal_state",
        "skipped_path",
    }
)

UNEXPECTED_TOOL_MESSAGE = "The tool failed unexpectedly."
TIMEOUT_MESSAGE = "The tool did not finish within its time limit."
INVALID_RESULT_MESSAGE = "The tool returned a result in an unexpected shape."
SECRET_BLOCKED_MESSAGE = "The tool result contained a private key, so it was withheld."
MEMORY_NOT_AUTHORIZED_MESSAGE = (
    "Saving a memory is not authorized for this turn. Only an explicit request in the current "
    "message (for example 'remember that ...') can allow it."
)
MEMORY_SECRET_MESSAGE = "That looks like a secret (a password, key or token), so it was not stored."
MEMORY_NOT_GROUNDED_MESSAGE = (
    "Only a fact stated in the current user message, in the user's own words, can be remembered."
)

WEB_MESSAGES = {
    ErrorType.WEB_NOT_AUTHORIZED: (
        "Web access is not authorized for this turn. Only an explicit request in the "
        "current message can allow it."
    ),
    ErrorType.EGRESS_BLOCKED_SENSITIVE: (
        "Web access was blocked because the request contains sensitive information."
    ),
    ErrorType.NETWORK_UNAVAILABLE: "The web is unavailable right now.",
    ErrorType.NO_RESULTS: "The web search returned no results.",
    ErrorType.TIMEOUT: "The web search timed out.",
    ErrorType.BUDGET_EXCEEDED: "The web budget for this turn is used up.",
    ErrorType.FETCH_FAILED: "The page could not be fetched.",
    ErrorType.RESULT_UNREPRESENTABLE: "The web result could not be represented within Zoe's limits.",
}


class ToolError(Exception):
    """A typed, safe tool failure raised by a catalog handler.

    ``message`` must be authored text (no exception text, no paths, no secrets).
    """

    def __init__(self, error_type: str, message: str, status: ResultStatus = ResultStatus.ERROR) -> None:
        super().__init__(message)
        self.error_type = error_type
        self.message = message
        self.status = status


class ProtocolError(ValueError):
    """A call record or wire payload violates the protocol (``malformed_call``)."""

    def __init__(self, detail: str) -> None:
        super().__init__(detail)
        self.detail = detail


# ---------------------------------------------------------------------------
# Execution-context marker (exactly one execution authority)
# ---------------------------------------------------------------------------

_EXECUTING: contextvars.ContextVar[str | None] = contextvars.ContextVar("zoe_tool_executing", default=None)


def in_tool_execution() -> bool:
    """True only inside ``ToolExecutor``'s execution step."""
    return _EXECUTING.get() is not None


def require_executor() -> None:
    """Catalog handlers call this so they cannot run outside the executor."""
    if not in_tool_execution():
        raise RuntimeError("structured tools run only through the ToolExecutor")


# ---------------------------------------------------------------------------
# ToolCall and ids
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ToolCall:
    """The internal tool-call record (§8.2). Frozen; arguments are deep-frozen.

    ``id``, ``turn_id`` and ``step`` come from the orchestrator and are
    authoritative. ``reason`` is optional free text (<= 200 chars) used only for
    logs and debug views; it never affects authorization.
    """

    tool: str
    arguments: Mapping[str, Any]
    tool_version: str
    id: str
    turn_id: str
    step: int
    reason: str | None = None
    protocol: str = PROTOCOL

    def __post_init__(self) -> None:
        if not isinstance(self.tool, str) or not _TOOL_NAME_RE.match(self.tool):
            raise ProtocolError("invalid_tool_name")
        if not isinstance(self.arguments, Mapping):
            raise ProtocolError("arguments_not_object")
        if not isinstance(self.tool_version, str) or not _VERSION_RE.match(self.tool_version):
            raise ProtocolError("invalid_tool_version")
        if not isinstance(self.id, str) or not _CALL_ID_RE.match(self.id):
            raise ProtocolError("invalid_call_id")
        if not isinstance(self.turn_id, str) or not _TURN_ID_RE.match(self.turn_id):
            raise ProtocolError("invalid_turn_id")
        if isinstance(self.step, bool) or not isinstance(self.step, int) or self.step < 1:
            raise ProtocolError("invalid_step")
        if self.reason is not None:
            if not isinstance(self.reason, str) or len(self.reason) > MAX_REASON_CHARS:
                raise ProtocolError("invalid_reason")
            if _CONTROL_CHARS.search(self.reason):
                raise ProtocolError("invalid_reason")
        if not isinstance(self.protocol, str) or not 1 <= len(self.protocol) <= 32:
            raise ProtocolError("invalid_protocol")
        object.__setattr__(self, "arguments", freeze(self.arguments))

    def arguments_dict(self) -> dict[str, Any]:
        return thaw(self.arguments)


class CallIdAllocator:
    """Orchestrator-side generator of call ids, unique for the session."""

    def __init__(self) -> None:
        self._issued: set[str] = set()
        self._lock = threading.Lock()

    def issue(self) -> str:
        with self._lock:
            while True:
                call_id = f"call_{uuid.uuid4().hex[:24]}"
                if call_id not in self._issued:
                    self._issued.add(call_id)
                    return call_id

    def issued(self, call_id: str) -> bool:
        return call_id in self._issued


def new_turn_id() -> str:
    """Orchestrator-side turn id."""
    return f"turn_{uuid.uuid4().hex[:16]}"


# ---------------------------------------------------------------------------
# Strict JSON
# ---------------------------------------------------------------------------


class StrictJSONError(ValueError):
    def __init__(self, detail: str) -> None:
        super().__init__(detail)
        self.detail = detail


def _reject_constant(_name: str) -> Any:
    raise StrictJSONError("non_finite_number")


def _object_pairs(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for key, value in pairs:
        if key in out:
            raise StrictJSONError("duplicate_key")
        out[key] = value
    return out


def _parse_int(text: str) -> int:
    if len(text) > MAX_JSON_NUMBER_CHARS:
        raise StrictJSONError("number_too_large")
    return int(text)


def _parse_float(text: str) -> float:
    if len(text) > MAX_JSON_NUMBER_CHARS:
        raise StrictJSONError("number_too_large")
    value = float(text)
    if not math.isfinite(value):
        raise StrictJSONError("non_finite_number")
    return value


def _check_json_value(value: Any, depth: int = 1) -> None:
    if depth > MAX_JSON_DEPTH:
        raise StrictJSONError("too_deep")
    if isinstance(value, str):
        try:
            value.encode("utf-8")
        except UnicodeEncodeError as exc:
            raise StrictJSONError("invalid_string") from exc
    elif isinstance(value, dict):
        for key, item in value.items():
            _check_json_value(key, depth + 1)
            _check_json_value(item, depth + 1)
    elif isinstance(value, list):
        for item in value:
            _check_json_value(item, depth + 1)


def strict_json_loads(text: str) -> Any:
    """Parse JSON strictly; raise ``StrictJSONError`` with a detail code. No repair."""
    if not isinstance(text, str):
        raise StrictJSONError("not_text")
    try:
        value = json.loads(
            text,
            object_pairs_hook=_object_pairs,
            parse_constant=_reject_constant,
            parse_int=_parse_int,
            parse_float=_parse_float,
        )
    except StrictJSONError:
        raise
    except RecursionError as exc:
        raise StrictJSONError("too_deep") from exc
    except (ValueError, TypeError) as exc:
        raise StrictJSONError("invalid_json") from exc
    _check_json_value(value)
    return value


# ---------------------------------------------------------------------------
# Qwen wire adapter
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ParseError:
    """Why a parse step produced no calls. ``type`` is always ``malformed_call``."""

    detail: str
    index: int | None = None
    type: str = MALFORMED_CALL


@dataclass(frozen=True)
class ParseResult:
    """Outcome of one parse step. On any error, ``calls`` is empty (fail closed)."""

    calls: tuple[ToolCall, ...] = ()
    error: ParseError | None = None
    fabricated_tool_response: bool = False
    fabricated_responses: int = 0  # number of stripped <tool_response> blocks / stray tags
    text: str = ""  # model prose outside tool-call blocks (not instructions)

    @property
    def ok(self) -> bool:
        return self.error is None


def _split_blocks(text: str) -> tuple[list[str], str, int]:
    """Return the raw ``<tool_call>`` payloads, the remaining prose and the fabrication count.

    One left-to-right scan; whichever tag starts first wins:

    - ``<tool_call>`` ... ``</tool_call>``: a call payload (no nesting).
    - ``<tool_response ...>`` ... ``</tool_response>``: fabricated by the model;
      stripped entirely, including any ``<tool_call>`` inside it. Without a
      closing tag it is stripped to the end of the output (fail closed).
    - a stray ``</tool_response>``: stripped.
    - a stray ``</tool_call>``: malformed.
    """
    payloads: list[str] = []
    prose: list[str] = []
    fabricated = 0
    position = 0
    length = len(text)
    while position < length:
        call_open = text.find(TOOL_CALL_OPEN, position)
        call_close = text.find(TOOL_CALL_CLOSE, position)
        response_open = _RESPONSE_OPEN.search(text, position)
        response_close = _RESPONSE_CLOSE.search(text, position)
        candidates = [
            (call_open, "call_open"),
            (call_close, "call_close"),
            (response_open.start() if response_open else -1, "response_open"),
            (response_close.start() if response_close else -1, "response_close"),
        ]
        found = [(index, kind) for index, kind in candidates if index != -1]
        if not found:
            prose.append(text[position:])
            break
        start, kind = min(found)
        prose.append(text[position:start])
        if kind == "call_close":
            raise ProtocolError("unmatched_close_tag")
        if kind == "response_open":
            fabricated += 1
            closing = _RESPONSE_CLOSE.search(text, response_open.end())
            position = closing.end() if closing else length
            continue
        if kind == "response_close":
            fabricated += 1
            position = response_close.end()
            continue
        body_start = start + len(TOOL_CALL_OPEN)
        end = text.find(TOOL_CALL_CLOSE, body_start)
        if end == -1:
            raise ProtocolError("unclosed_block")
        body = text[body_start:end]
        if TOOL_CALL_OPEN in body:
            raise ProtocolError("nested_block")
        payloads.append(body)
        position = end + len(TOOL_CALL_CLOSE)
    return payloads, "".join(prose).strip(), fabricated


class QwenToolCallAdapter:
    """Map Qwen's native ``{"name", "arguments"}`` wire calls to ``ToolCall`` records."""

    def __init__(self, registry: "ToolRegistry | None" = None, ids: CallIdAllocator | None = None) -> None:
        if registry is None:
            from tools.tool_catalog import get_tool_registry

            registry = get_tool_registry()
        self.registry = registry
        self.ids = ids or CallIdAllocator()

    def parse(self, model_output: str, *, turn_id: str, step: int) -> ParseResult:
        """Parse one model output. ``turn_id`` and ``step`` are the orchestrator's."""
        if not isinstance(model_output, str):
            return ParseResult(error=ParseError("not_text"))
        if len(model_output) > MAX_MODEL_OUTPUT_CHARS:
            return ParseResult(error=ParseError("oversized_output"))

        # §10.2: a model-written <tool_response> is stripped by the scan (never a
        # tool result, call or authorization); parsing continues after it.
        try:
            payloads, prose, fabricated_count = _split_blocks(model_output)
        except ProtocolError as exc:
            seen = bool(_RESPONSE_OPEN.search(model_output) or _RESPONSE_CLOSE.search(model_output))
            return ParseResult(error=ParseError(exc.detail), fabricated_tool_response=seen)
        fabricated = fabricated_count > 0
        if fabricated:
            audit_logger.warning(
                "fabricated_tool_response turn=%s step=%s count=%d", turn_id, step, fabricated_count
            )
        if len(payloads) > MAX_CALLS_PER_STEP:
            return ParseResult(error=ParseError("too_many_calls"), fabricated_tool_response=fabricated)

        drafts: list[dict[str, Any]] = []
        for index, payload in enumerate(payloads):
            if len(payload) > MAX_TOOL_CALL_CHARS:
                return ParseResult(error=ParseError("oversized_call", index), fabricated_tool_response=fabricated)
            try:
                drafts.append(self._draft(strict_json_loads(payload)))
            except (StrictJSONError, ProtocolError) as exc:
                return ParseResult(error=ParseError(exc.detail, index), fabricated_tool_response=fabricated)

        calls: list[ToolCall] = []
        for index, draft in enumerate(drafts):
            try:
                calls.append(
                    ToolCall(
                        tool=draft["tool"],
                        arguments=draft["arguments"],
                        tool_version=draft["tool_version"],
                        id=self.ids.issue(),
                        turn_id=turn_id,
                        step=step,
                        reason=draft["reason"],
                    )
                )
            except ProtocolError as exc:
                return ParseResult(error=ParseError(exc.detail, index), fabricated_tool_response=fabricated)
        return ParseResult(
            calls=tuple(calls),
            fabricated_tool_response=fabricated,
            fabricated_responses=fabricated_count,
            text=prose,
        )

    def _draft(self, wire: Any) -> dict[str, Any]:
        if not isinstance(wire, dict):
            raise ProtocolError("call_not_object")
        unknown = set(wire) - _WIRE_KEYS - _IGNORED_WIRE_KEYS
        if unknown:
            raise ProtocolError("unknown_call_field")
        # Model-supplied id / call_id / turn_id / step: dropped here, unread.
        wire = {key: value for key, value in wire.items() if key not in _IGNORED_WIRE_KEYS}
        name = wire.get("name")
        if not isinstance(name, str) or not _TOOL_NAME_RE.match(name):
            raise ProtocolError("invalid_tool_name")
        if "arguments" not in wire or not isinstance(wire["arguments"], dict):
            raise ProtocolError("arguments_not_object")
        reason = wire.get("reason")
        if reason is not None and (not isinstance(reason, str) or len(reason) > MAX_REASON_CHARS):
            raise ProtocolError("invalid_reason")
        tool = self.registry.resolve_wire_name(name)
        definition = self.registry.get(tool)
        version = wire.get("tool_version")
        if version is None:
            version = definition.version_string if definition is not None else "1"
        if not isinstance(version, str):
            raise ProtocolError("invalid_tool_version")
        return {"tool": tool, "arguments": wire["arguments"], "tool_version": version, "reason": reason}


# ---------------------------------------------------------------------------
# Policy gate
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PolicyDecision:
    allowed: bool
    status: ResultStatus = ResultStatus.SUCCESS
    error_type: str | None = None
    message: str = ""


ALLOW = PolicyDecision(True)


class PolicyGate:
    """Authorization for one validated call (§22.3).

    Inputs are closed: the tool definition and the validated arguments. Web
    tools additionally read the turn-scoped B2 decision, which only the current
    user message can produce. The memory tool reads the analogous turn-scoped
    memory authorization (explicit remember request in the current user
    message, set by the tool loop at turn start). ``ToolCall.reason`` is never
    passed in.
    """

    def __init__(self, path_arguments: Mapping[str, tuple[str, str]] | None = None) -> None:
        if path_arguments is None:
            from tools.tool_catalog import FILESYSTEM_PATH_ARGUMENTS

            path_arguments = FILESYSTEM_PATH_ARGUMENTS
        self.path_arguments = dict(path_arguments)

    def check(self, definition: "ToolDefinition", arguments: Mapping[str, Any]) -> PolicyDecision:
        if not definition.available:
            return PolicyDecision(False, ResultStatus.DENIED, PERMISSION_DENIED, "That tool is not available.")
        if definition.permission is PermissionClass.FILESYSTEM_READ:
            return self._check_filesystem(definition, arguments)
        if definition.permission is PermissionClass.NETWORK:
            return self._check_web()
        if definition.permission is PermissionClass.MEMORY_WRITE:
            return self._check_memory(definition, arguments)
        if definition.permission in {PermissionClass.COMPUTE, PermissionClass.CLOCK, PermissionClass.CODE_SEARCH}:
            return ALLOW
        return PolicyDecision(False, ResultStatus.DENIED, PERMISSION_DENIED, "That tool is not permitted.")

    def _check_filesystem(self, definition: "ToolDefinition", arguments: Mapping[str, Any]) -> PolicyDecision:
        # B1 is authoritative: resolve with the same resolver the tool uses.
        from tools.fs_policy import AccessMode, FilesystemError, resolve_in_workspace

        spec = self.path_arguments.get(definition.name)
        if spec is None:
            return PolicyDecision(False, ResultStatus.DENIED, PERMISSION_DENIED, "That tool is not permitted.")
        argument, mode = spec
        try:
            resolve_in_workspace(arguments[argument], AccessMode(mode))
        except FilesystemError as exc:
            status = ResultStatus.DENIED if exc.error_type in FILESYSTEM_DENIED_TYPES else ResultStatus.ERROR
            return PolicyDecision(False, status, exc.error_type, str(exc))
        return ALLOW

    def _check_web(self) -> PolicyDecision:
        # B2 is authoritative; ``gated_search`` re-checks everything at call time.
        from web.policy import current_decision, is_offline

        if is_offline():
            error = ErrorType.NETWORK_UNAVAILABLE
            return PolicyDecision(False, ResultStatus.DENIED, error.value, WEB_MESSAGES[error])
        decision = current_decision()
        if not decision.allowed:
            error = decision.error_type or ErrorType.WEB_NOT_AUTHORIZED
            return PolicyDecision(False, ResultStatus.DENIED, error.value, WEB_MESSAGES[error])
        return ALLOW


    def _check_memory(self, definition: "ToolDefinition", arguments: Mapping[str, Any]) -> PolicyDecision:
        # Exactly the ``remember`` tool; authorized only by the current user
        # message (turn-scoped, fixed at turn start, never by history, tool
        # results or ``reason``) and only inside an active tool loop.
        from tools.tool_loop import memory_fact_grounded, memory_write_authorized
        from web.policy import scan_message_secrets

        if definition.name != "remember":
            return PolicyDecision(False, ResultStatus.DENIED, PERMISSION_DENIED, "That tool is not permitted.")
        if not memory_write_authorized():
            return PolicyDecision(False, ResultStatus.DENIED, PERMISSION_DENIED, MEMORY_NOT_AUTHORIZED_MESSAGE)
        fact = arguments.get("fact")
        if not isinstance(fact, str):
            return PolicyDecision(False, ResultStatus.DENIED, PERMISSION_DENIED, "That tool is not permitted.")
        scan = scan_and_redact(fact)  # Phase C/B1 secret scan, plus B2's message secret scan
        if scan.blocked or scan.redacted_lines or scan_message_secrets(fact):
            return PolicyDecision(False, ResultStatus.DENIED, SENSITIVE_CONTENT, MEMORY_SECRET_MESSAGE)
        if not memory_fact_grounded(fact):
            return PolicyDecision(False, ResultStatus.DENIED, PERMISSION_DENIED, MEMORY_NOT_GROUNDED_MESSAGE)
        return ALLOW


# ---------------------------------------------------------------------------
# Executor
# ---------------------------------------------------------------------------


class _Timeout(Exception):
    pass


def _run_with_timeout(handler: Any, arguments: dict[str, Any], timeout_s: float, call_id: str) -> Any:
    """Run ``handler`` in a daemon thread that inherits the caller's context.

    On timeout the result is discarded (the thread cannot be killed; its
    output never reaches the envelope).
    """
    context = contextvars.copy_context()
    box: dict[str, Any] = {}
    done = threading.Event()

    def _invoke() -> Any:
        _EXECUTING.set(call_id)
        return handler(**arguments)

    def _runner() -> None:
        try:
            box["value"] = context.run(_invoke)
        except BaseException as exc:  # re-raised in the caller below
            box["error"] = exc
        finally:
            done.set()

    worker = threading.Thread(target=_runner, name=f"zoe-tool-{call_id}", daemon=True)
    worker.start()
    if not done.wait(timeout_s):
        raise _Timeout
    if "error" in box:
        raise box["error"]
    return box["value"]


def _scan_payload(value: Any) -> tuple[Any, int, bool]:
    """Secret-scan every string in a payload: (payload, redacted_lines, blocked)."""
    if isinstance(value, str):
        scan = scan_and_redact(value)
        if scan.blocked:
            return "", 0, True
        if scan.redacted_lines:
            return scan.text, scan.redacted_lines, False
        return value, 0, False
    if isinstance(value, Mapping):
        out: dict[str, Any] = {}
        total = 0
        for key, item in value.items():
            out[key], count, blocked = _scan_payload(item)
            if blocked:
                return None, 0, True
            total += count
        return out, total, False
    if isinstance(value, (list, tuple)):
        items: list[Any] = []
        total = 0
        for item in value:
            scanned, count, blocked = _scan_payload(item)
            if blocked:
                return None, 0, True
            items.append(scanned)
            total += count
        return items, total, False
    return value, 0, False


class ToolExecutor:
    """The single execution authority for structured tool calls (§8.5, §22)."""

    def __init__(self, registry: "ToolRegistry | None" = None, gate: PolicyGate | None = None) -> None:
        if registry is None:
            from tools.tool_catalog import get_tool_registry

            registry = get_tool_registry()
        self.registry = registry
        self.gate = gate or PolicyGate()
        self._executed: set[str] = set()
        self._lock = threading.Lock()

    # -- envelopes ---------------------------------------------------------

    @staticmethod
    def _failure(
        call: ToolCall,
        tool: str,
        status: ResultStatus,
        error_type: str,
        message: str,
        *,
        trust: str = "untrusted",
        metadata: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        meta = {"turn_id": call.turn_id, "step": call.step, **(metadata or {})}
        if error_type in CANONICAL_ERROR_TYPES:
            return error_envelope(
                tool, status, ErrorType(error_type), message, call_id=call.id, trust=trust, metadata=meta
            )
        envelope = make_envelope(tool, status, call_id=call.id, trust=trust, metadata=meta)
        envelope["error"] = {"type": error_type, "message": message, "retryable": False}
        return envelope

    # -- execution ---------------------------------------------------------

    def execute(self, call: ToolCall) -> dict[str, Any]:
        """Run one call through the fixed pipeline; always return an envelope."""
        try:
            return self._execute(call)
        except Exception as exc:  # last-resort boundary: never raise, never leak
            log_safe_exception(logger, "Tool executor", exc)
            if not isinstance(call, ToolCall):
                raise TypeError("execute() needs a ToolCall") from None
            return self._failure(call, call.tool, ResultStatus.ERROR, INTERNAL_ERROR, UNEXPECTED_TOOL_MESSAGE)

    def _execute(self, call: ToolCall) -> dict[str, Any]:
        if not isinstance(call, ToolCall):
            raise TypeError("execute() needs a ToolCall")
        with self._lock:
            if call.id in self._executed:
                return self._failure(call, call.tool, ResultStatus.ERROR, MALFORMED_CALL, "This call id was already used.")
            self._executed.add(call.id)

        # 1. Registry lookup.
        definition = self.registry.get(call.tool)
        if definition is None:
            return self._failure(call, call.tool, ResultStatus.ERROR, UNKNOWN_TOOL, "There is no tool with that name.")
        tool = definition.name
        trust = definition.trust.value

        # 2. Protocol / version validation.
        if call.protocol != PROTOCOL:
            return self._failure(call, tool, ResultStatus.ERROR, UNSUPPORTED_VERSION, "Unsupported tool protocol.", trust=trust)
        if call.tool_version.split(".", 1)[0] != definition.version_string:
            return self._failure(
                call, tool, ResultStatus.ERROR, UNSUPPORTED_VERSION, "Unsupported tool version.", trust=trust
            )

        # 3. Argument validation (closed schema, defaults applied).
        try:
            arguments = definition.validate_arguments(call.arguments_dict())
        except ArgumentError as exc:
            return self._failure(
                call, tool, ResultStatus.ERROR, INVALID_ARGUMENTS, f"Invalid arguments: {exc.field} {exc.reason}.", trust=trust
            )

        # 4. Policy gate (reason is not an input).
        decision = self.gate.check(definition, arguments)
        audit_logger.info(
            "tool_decision call=%s turn=%s step=%s tool=%s decision=%s error_type=%s",
            call.id,
            call.turn_id,
            call.step,
            definition.id,
            "allow" if decision.allowed else "deny",
            decision.error_type or "-",
        )
        if not decision.allowed:
            return self._failure(
                call, tool, decision.status, decision.error_type or PERMISSION_DENIED, decision.message, trust=trust
            )

        # 5/6. Timeout boundary around tool execution.
        started = time.perf_counter()
        try:
            payload = _run_with_timeout(definition.handler, arguments, definition.timeout_s, call.id)
        except _Timeout:
            logger.warning("Tool %s timed out after %.1fs", definition.id, definition.timeout_s)
            return self._failure(call, tool, ResultStatus.TIMEOUT, ErrorType.TIMEOUT.value, TIMEOUT_MESSAGE, trust=trust)
        except ToolError as exc:
            return self._failure(call, tool, exc.status, exc.error_type, exc.message, trust=trust)
        except TypedSafeError as exc:  # B3 calculator errors (and other typed safe errors)
            return self._failure(call, tool, ResultStatus.ERROR, exc.error_type, exc.safe_message, trust=trust)
        except Exception as exc:
            from tools.fs_policy import FilesystemError

            if isinstance(exc, FilesystemError):  # B1 typed errors keep their types
                status = ResultStatus.DENIED if exc.error_type in FILESYSTEM_DENIED_TYPES else ResultStatus.ERROR
                return self._failure(call, tool, status, exc.error_type, str(exc), trust=trust)
            log_safe_exception(logger, f"Tool {definition.id}", exc)
            return self._failure(call, tool, ResultStatus.ERROR, INTERNAL_ERROR, UNEXPECTED_TOOL_MESSAGE, trust=trust)
        duration_ms = int((time.perf_counter() - started) * 1000)

        # 7. Secret scan over every string in the payload.
        scanned, redactions, blocked = _scan_payload(payload)
        if blocked:
            return self._failure(call, tool, ResultStatus.DENIED, SENSITIVE_CONTENT, SECRET_BLOCKED_MESSAGE, trust=trust)

        # 8. Output schema validation.
        try:
            result = definition.validate_result(scanned)
        except ArgumentError:
            logger.warning("Tool %s returned an invalid result shape", definition.id)
            return self._failure(call, tool, ResultStatus.ERROR, INTERNAL_ERROR, INVALID_RESULT_MESSAGE, trust=trust)

        # 9. Universal result envelope (per-tool limits, then global limits).
        source: dict[str, Any] = {"kind": definition.source_kind}
        if definition.source_kind == "file" and isinstance(result.get("path"), str):
            source["path"] = result["path"]
        return bound_result(
            tool,
            result,
            trust=trust,
            source=source,
            metadata={
                "duration_ms": duration_ms,
                # Lines redacted by the tool itself (B1 reports them) plus the executor scan.
                "redactions": redactions + (result["redactions"] if isinstance(result.get("redactions"), int) else 0),
                "turn_id": call.turn_id,
                "step": call.step,
            },
            tool_limits=definition.limits,
            call_id=call.id,
        )


_default_executor: ToolExecutor | None = None
_default_lock = threading.Lock()


def get_tool_executor() -> ToolExecutor:
    """The process-wide executor instance (one execution authority)."""
    global _default_executor
    with _default_lock:
        if _default_executor is None:
            _default_executor = ToolExecutor()
        return _default_executor


def execute_tool_call(call: ToolCall) -> dict[str, Any]:
    """Execute one structured call through the single ToolExecutor."""
    return get_tool_executor().execute(call)
